### ISSUE TITLE
Create interactive docs

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/fq-imjoy#21]
ImJoy plugins can now be integrated into the documentation, see https://kaibu.org/docs/#/

would be great to have this for FQ as well. 

1. create new folder `docs-interactive`, akin to docs folder in example above
2. use this for github pages, will be rendered automatically
3. link from landing page

also, referring to the binder usage might be interesting, since people don't need a local installation. 

to upload their data, they would need to provide a zip archive ... 

thanks @oeway for all the suggestions.

**Comment by muellerflorian** [comment]
one file that needs customization is https://github.com/imjoy-team/kaibu/blob/master/docs/index.html

**Comment by oeway** [comment]
@muellerflorian I documented the interactive imjoy docs here: https://docs.imjoy.io/ Please follow the instructions and let me know if it works for you.

**Comment by muellerflorian** [comment]
created in  separate repository: https://github.com/fish-quant/fq-interactive-docs
