### ISSUE TITLE
'Analyze current image' not working

### ISSUE THREAD

**Issue by jstitlow** [fish-quant/fq-imjoy#27]
Greetings, this is a really cool project! Have been using FQ in Matlab for years and we now have a quirky situation that calls for open source smFISH analysis with a GUI, so thanks!

**Describe the bug**
Spot detection with FG-Imjoy takes a very long time. I suspect there is something wrong, because file processing has not finished after several hours, even though I have cropped the image down to 115x115x5 and chosen a threshold that detects only < 100 spots. 

Shortly after the app hangs, there is a Python error message in the Chrome log:
`  File "/Users/joshtitlow/Library/Python/3.7/lib/python/site-packages/matplotlib/figure.py", line 428, in show
    manager = getattr(self.canvas, 'manager')
AttributeError: 'FigureCanvasAgg' object has no attribute 'manager'
`

**To Reproduce**
Not sure, 
* setup a new conda environment
* installed with pip as suggested
* opened jupyter notebook with `imjoy --jupyter`
* installed FQ plugin by clicking + plugin and pasting the GitHub repo URL. 
* FQ app runs fine through Spot Detection, then hangs when I try to process the selected file

**Logs**
 - Plugin log
 
[FISH-QUANT_nlnxi1609564245421.txt](https://github.com/fish-quant/fq-imjoy/files/5759796/FISH-QUANT_nlnxi1609564245421.txt)

 - Browser console log

[Chrome_console_FG-Imjoy.log](https://github.com/fish-quant/fq-imjoy/files/5759798/Chrome_console_FG-Imjoy.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/5816582/103451148-7a8c1580-4c8e-11eb-85b8-5abc2cebe31f.png)

**Versions:**
 - OS: macOS Mojave 10.14.6, 2.5 GHz i7, 16 GB RAM
 - Browser: Chrome v87.0.4280.88 (Official Build) (x86_64)
 - FISH-quant: installed plugin from within Imjoy by pointing to the Github repo 
 - FISH-quant interface

**Additional context**

**Comment by jstitlow** [comment]
**UPDATE**

* The behavior of `Analyze current image` is slightly different when running it after selecting `Select smaller region to test analysis`, i.e., output in the workspace says 'Processing File: spot detection' as opposed to being stuck on 'Detection with threshold...'. 

* Appears to be breaking because of Matplotlib: `AttributeError: 'FigureCanvasAgg' object has no attribute 'manager'`. I tried changing the matplotlib version based on [this github post](https://github.com/matterport/Mask_RCNN/issues/1171) but the FISHQUANT plugin uninstalled it and returned to its preferred version, presumably the intended behavior. 

Any idea how to fix the AttributeError or do you think there is a different problem?

Thanks!
j

**Comment by muellerflorian** [comment]
Thanks for the detailed bug report. For the moment, I can't reproduce it (but I'm not on a Mac). 

a first comment, we pinned the versions of all libraries (with the hope to avoid problems like this :-) ): https://github.com/fish-quant/big-fish/blob/master/requirements.txt

could you try one thing? for demo purposes, you can actually **run the engine on myminder.org**. For this, you have to
1. connect to a mybinder engine (button `+ Add MyBinder-Engine` in the engine meny in the upper right corner).
2. Run FISH-quant plugin on this engine (from the dropdown menu when clicking on the puzzle symbol left of the plugin name). Starting might take a bit of time. 
3. after starting FISH-quant, you can get test data by clicking on the "get zipped data".
4.  from there one, the workflow is as usual (most fields contain some useful default values). 

If this works, you can connect the plugin to your local engine, and attempt to analyze the test data with ImJoy running locally.

In the meantime, I'm going to have a closer look myself.

**Comment by jstitlow** [comment]
Thanks. 
* the analysis works in my local engine if I untick `create plots`
* the analysis worked worth the binder image
* could you please let me know how to "connect the plugin to your local engine"

**Comment by muellerflorian** [comment]
thanks for the feedback. so there really seems to be an issue with creating Matplotlib plots locally. 

**concerning your question**. If you click on puzzle symbol next to the plugin name, you will get  a dropdown menu. Here, all engines ImJoy is connected to will be shown. The local one will be called "Jupyter Notebook" if you kept the default name. 

![image](https://user-images.githubusercontent.com/10832779/103666412-e6af9780-4f74-11eb-91a9-08d533fd5850.png)

**Comment by oeway** [comment]
Hi @jstitlow I cannot reproduce your issue on my Mac, but I made a custom version for you with matplotlib pinned to `2.2.3`, could you please try it here: [![launch ImJoy](https://imjoy.io/static/badge/launch-imjoy-badge.svg)](https://imjoy.io/#/app?w=fq-test&plugin=https%3A%2F%2Fgithub.com%2Ffish-quant%2Fbig-fish%2Fblob%2Ffix-matplotlib-mac%2FFISH-quant.imjoy.html) and let us know if it works for you. 

The only changed I made is to pin matplotlib to 2.2.3 [here](https://github.com/fish-quant/big-fish/blob/fix-matplotlib-mac/requirements.txt#L5).

**Comment by jstitlow** [comment]
Thanks, the custom version gives the same result. 
Something could be wrong with my conda environment. Can we exchange .yml files (mine is [here](https://drive.google.com/file/d/14W7O2gwcmCE468dTHbsn0rv7X3ZlBO55/view?usp=sharing))?
Maybe mine will reproduce the error in your environment, or yours will work in my environment?

**Regarding Florian's suggestion to switch to the local jupyter engine**, when I select the Jupyter Notebook engine, the plugin reloads and no longer works. Here is what I did:

1. open imjoy app
2. add MyBinder engine
3. click FISH-QUANT puzzle icon and select Jupyter Notebook
4. it asks me to `Please connect to the plugin engine`
5. I click the `Jupyter-Engine Manager` puzzle icon and select reload
6. it says `Failed to connect to plugin engine`
7. I click the spaceship icon and `Add Jupyter Engine`
8. The engine connects, but FISH-QUANT behavior is the same

Does this experiment confirm that my jupyter kernel is the issue, since I am now presumably running a working FQ plugin from binder on my local machine?

Thanks, and sorry for the distraction.

**Comment by oeway** [comment]
Hi, I just created new environment based on your yml file, and I can successfully run the plugin, see the screen recording below:

![fish-quant-startup](https://user-images.githubusercontent.com/478667/103693961-6f8cfa00-4f9a-11eb-99b3-01671ed73d72.gif)

As you see above, to make sure you are using your local engine, you need to 1) the Jupyter Engine engine is connected 2) It is selected as the plugin for fish-quant.

However, I just noticed one thing in your error log:
```
JupyterConnection.js:62 Traceback (most recent call last):
  File "/Users/joshtitlow/Library/Python/3.7/lib/python/site-packages/matplotlib/figure.py", line 428, in show
    manager = getattr(self.canvas, 'manager')
AttributeError: 'FigureCanvasAgg' object has no attribute 'manager'
```

This perhaps means you are running your system installed Python instead of the one from conda, this means the PATH env variable is not configured correctly. Could you try to run `which python3` and you should see something like `/Users/wei.ouyang/miniconda3/envs/fq-imjoy/bin/python3`

Then you can also try, see if it runs with this:
```bash
python3 -m imjoy --jupyter
```

**Comment by jstitlow** [comment]
Thanks for the suggestions and screen recording. 

It's working now. 

I ran `imjoy --jupyter` from conda base environment, and when I opened imjoy, it looks to have setup the environment properly.

**Comment by muellerflorian** [comment]
little follow-up.

thanks @oeway for figuring this out!

@jstitlow: any suggestions for how we can improve the documentation to avoid this problem for future users?

**Comment by jstitlow** [comment]
I’m still not sure what the issue was exactly.
I think it would just get filed under the existing FAQ ‘Remove Conda Environment’
The solution was to start imjoy from the conda base environment, so maybe add an additional suggestion to the existing FAQ as shown below.
1.    Open anaconda terminal
2.    Activate base environment: conda deactivate
3.    Remove fq-imjoy environment: conda env remove --name fq-imjoy
or


  1.  Open anaconda terminal
  2.  Activate base environment: `conda activate`
  3.  Run imjoy from base environment: `imjoy --jupyter`
  4.  When imjoy opens, it will setup the environment properly

**Comment by muellerflorian** [comment]
thanks for the feedback.

based on Wei's comments, it seems that your initial attempts were done with the system python and not the anaconda one. 

Ideally, we would like to avoid running it out of the base environment since this environment might get easily corrupted by other updates.  The plugin engine doesn't handle the environments, it runs in whatever environment you decided to install it. 

I'm still surprised, that it didn't work when using a dedicated environment ...  essentially what you need to do:

# Installation (only once)
1. `conda create --name fq-imjoy python=3.7`
2. `conda activate fq-imjoy`
3. `pip install -U imjoy`

# Starting engine (each time you want to use it).
1. `conda activate fq-imjoy`
2. `imjoy --jupyter`
