### ISSUE TITLE
File loading is not working anymore

### ISSUE THREAD

**Issue by xcarmengrandix** [fish-quant/fq-imjoy#38]
Hello, I've always managed to load the files without any problem but since yesterday FISH-quant is not scanning the folder anymore. I tried both on Chrome and Safari. 
The same happens with the demo data provided by you.
Any suggestion?

**Comment by muellerflorian** [comment]
Hello, sorry for the issues you encountered. 

can you provide some more details

1. which operating system are you using.
2. if your press the button "scan" the files are not listed any more? is there any error message? 
3. can you provide the console log as a text file (chrome, right mouse click, choose 'inspect', in the panel that opens select the tab "Console", right click and choose "save as".

**Comment by xcarmengrandix** [comment]
Hi, thanks for the quick answer. I'm using Windows 10. When I click "scan" nothing happens and there is no error message. 

Here is the consol log:
[imjoy.io-1626423495917.log](https://github.com/fish-quant/fq-imjoy/files/6829064/imjoy.io-1626423495917.log)

**Comment by muellerflorian** [comment]
thanks. I can reproduce this. will try to fix this quickly,

**Comment by muellerflorian** [comment]
I think I found the problem. Will be resolved with #37 .

**Comment by xcarmengrandix** [comment]
> I think I found the problem. Will be resolved with #37 .

It now works, many thanks!
