### ISSUE TITLE
Can't properly preprocess the images

### ISSUE THREAD

**Issue by HaofeiGe** [fish-quant/fq-imjoy#52]
Hi~I'm a fresher and have a problem here. I can only successfully preprocess the example images from fq-segmentation. But when I use the example images from fq-imjoy or my images, it gives me wrong results like this ↓ 。I am using a Windows 10 device.
![D$UIO_0@Z5MJK)8(PO 90B](https://user-images.githubusercontent.com/108987241/178109127-ca559930-8c77-4214-86d7-e44a82c55b7a.png)

**Comment by muellerflorian** [comment]
Hello, we will nee more information to check what you think is going on. the above shown screenshot looks not wrong to me. you would expect for a given channel (dapi in this case) to have a settings file (.json) and an image file (.png). that's what you have. what do you think it not working? if you have error messages, please also provide them.

**Comment by HaofeiGe** [comment]
> Hello, we will nee more information to check what you think is going on. the above shown screenshot looks not wrong to me. you would expect for a given channel (dapi in this case) to have a settings file (.json) and an image file (.png). that's what you have. what do you think it not working? if you have error messages, please also provide them.

Hello~I'm sorry about my discription. 
Firstly, intuitively, the image file (.png) from preprocess program are different.
![~G_LX GPSDM@HANTJPPXHCD](https://user-images.githubusercontent.com/108987241/178253415-b5701c25-81b3-40ba-b5b0-14a235fefd42.png)
Secondly, it will error in "SegmentObjects" or "SegmentCellsNuclei". Here are Log (Preprocess), Log(SegmentObjects) and Log (SegmentCellsNuclei).
[PreProcess_iul3d1657536566481.txt](https://github.com/fish-quant/fq-imjoy/files/9083457/PreProcess_iul3d1657536566481.txt)
[SegmentObjects_9zhve1657536571643.txt](https://github.com/fish-quant/fq-imjoy/files/9083458/SegmentObjects_9zhve1657536571643.txt)
[SegmentCellsNuclei_u91lb1657536569410.txt](https://github.com/fish-quant/fq-imjoy/files/9083461/SegmentCellsNuclei_u91lb1657536569410.txt)

**Comment by HaofeiGe** [comment]
> Hello, we will nee more information to check what you think is going on. the above shown screenshot looks not wrong to me. you would expect for a given channel (dapi in this case) to have a settings file (.json) and an image file (.png). that's what you have. what do you think it not working? if you have error messages, please also provide them.

Looking forward to your reply~Thanks a lot~O(∩_∩)O

**Comment by HaofeiGe** [comment]
> Hello, we will nee more information to check what you think is going on. the above shown screenshot looks not wrong to me. you would expect for a given channel (dapi in this case) to have a settings file (.json) and an image file (.png). that's what you have. what do you think it not working? if you have error messages, please also provide them.

Hello. I'm sorry about my discription.
Firstly, intuitively, the image file (.png) from preprocess program are different.
![~G_LX GPSDM@HANTJPPXHCD](https://user-images.githubusercontent.com/108987241/178255595-0d5e050e-ae50-42d2-ab05-2806b473278f.png)
Secondly, it will error in "SegmentObjects" or "SegmentCellsNuclei". Here are Log (Preprocess), Log(SegmentObjects) and Log (SegmentCellsNuclei).
[PreProcess_iul3d1657536566481.txt](https://github.com/fish-quant/fq-imjoy/files/9083542/PreProcess_iul3d1657536566481.txt)
[SegmentObjects_9zhve1657536571643.txt](https://github.com/fish-quant/fq-imjoy/files/9083548/SegmentObjects_9zhve1657536571643.txt)
[SegmentCellsNuclei_u91lb1657536569410.txt](https://github.com/fish-quant/fq-imjoy/files/9083553/SegmentCellsNuclei_u91lb1657536569410.txt)
Looking forward to your reply. Thanks a lot!

**Comment by HaofeiGe** [comment]
> Hello, sorry for the late reply. was traveling.
> 
> not sure what's going on. can you send the raw 3d images and also the projected ones (wetransfer or something like that)?
> 
> my email: [muellerf.research@gmail.com](mailto:muellerf.research@gmail.com)

Hello~I'm so sorry for my naive. I've found the reason—— if the input image for "preprocess" is a 2D (max indensity), it will cause this problem. When I convert the raw image to 3D tif image in ImageJ, no wrong occurs. Thx a lot for your attention.

But resently, I have a New Problem. TaT. Some smFISH images stuck in Filter image, when sigma-xy ≤0.5.
![DO0{@{8QOQ39D3_3I72@4QE](https://user-images.githubusercontent.com/108987241/182750067-d82349e4-f9c0-40cf-9c77-3fc06b093d3d.png)
Log(FISH-QUANT) is offered.
[FISH-QUANT_ia8bn1659579753942.txt](https://github.com/fish-quant/fq-imjoy/files/9256235/FISH-QUANT_ia8bn1659579753942.txt)
The raw image is sent to your email.
Thanks for help~

**Comment by Mariateresa91** [comment]
Hi all,
I am having the same problem discussed above. I am trying to segment my 2D .png images to perform then spot quantification: all images are single-plane, 2221x2221px each. However, when I use PreProcess and SegmentObjects I get something like this:

![image](https://github.com/fish-quant/fq-imjoy/assets/155670828/4e57a59b-120f-4270-ade2-8581f54ff46e)

I have also tried using .tif files, and I get the same problem.

Do you know what could be the reason of this?

Here are the parameters I use: 

![image](https://github.com/fish-quant/fq-imjoy/assets/155670828/4dce3c93-5152-4432-ba12-a0c08563c6d1)

Thank you in advance!
Mariateresa

**Comment by HaofeiGe** [comment]
> Hi all, I am having the same problem discussed above. I am trying to segment my 2D .png images to perform then spot quantification: all images are single-plane, 2221x2221px each. However, when I use PreProcess and SegmentObjects I get something like this:
> 
> ![image](https://private-user-images.githubusercontent.com/155670828/333702292-4e57a59b-120f-4270-ade2-8581f54ff46e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTUwNTYsIm5iZiI6MTcxNjY5NDc1NiwicGF0aCI6Ii8xNTU2NzA4MjgvMzMzNzAyMjkyLTRlNTdhNTliLTEyMGYtNDI3MC1hZGUyLTg1ODFmNTRmZjQ2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMzM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTE1ODNlZDBkNDQxYzQ2NzAxZTlmMTRiOTY2MTNmZWM4YTFjZTU4ODhlYmIwMjk3YjJkYTVjYjkyZjk3OTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CehS4kx-qyISz836-tj9N2CFyBetDIUvOhJhsXkJzTs)
> 
> I have also tried using .tif files, and I get the same problem.
> 
> Do you know what could be the reason of this?
> 
> Here are the parameters I use:
> 
> ![image](https://private-user-images.githubusercontent.com/155670828/333702882-4dce3c93-5152-4432-ba12-a0c08563c6d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTUwNTYsIm5iZiI6MTcxNjY5NDc1NiwicGF0aCI6Ii8xNTU2NzA4MjgvMzMzNzAyODgyLTRkY2UzYzkzLTUxNTItNDQzMi1iYTEyLWEwYzA4NTYzYzZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMzM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWJjYTMyM2VmNzFhZTNhOWFkZTg4YTc1OGZiMmYyZWZmYzk0ZDdkYzE1YjhiNWRmZDgwYmM1NDA1YjcwYzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BX6zv_sI_UBnxQSnrzMUEvDrP8HSsPZ51Fkv1L1FvJY)
> 
> Thank you in advance! Mariateresa

Hi~I give up processing smFISH image on Imjoy. Using the Python version of BigFISH(https://big-fish.readthedocs.io/en/stable/) is a better choice. It really runs very well, whether it's looping through multiple smFISH images or the running speed.

**Comment by HaofeiGe** [comment]
> Hi all, I am having the same problem discussed above. I am trying to segment my 2D .png images to perform then spot quantification: all images are single-plane, 2221x2221px each. However, when I use PreProcess and SegmentObjects I get something like this:
> 
> ![image](https://private-user-images.githubusercontent.com/155670828/333702292-4e57a59b-120f-4270-ade2-8581f54ff46e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTUwNTYsIm5iZiI6MTcxNjY5NDc1NiwicGF0aCI6Ii8xNTU2NzA4MjgvMzMzNzAyMjkyLTRlNTdhNTliLTEyMGYtNDI3MC1hZGUyLTg1ODFmNTRmZjQ2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMzM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTE1ODNlZDBkNDQxYzQ2NzAxZTlmMTRiOTY2MTNmZWM4YTFjZTU4ODhlYmIwMjk3YjJkYTVjYjkyZjk3OTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CehS4kx-qyISz836-tj9N2CFyBetDIUvOhJhsXkJzTs)
> 
> I have also tried using .tif files, and I get the same problem.
> 
> Do you know what could be the reason of this?
> 
> Here are the parameters I use:
> 
> ![image](https://private-user-images.githubusercontent.com/155670828/333702882-4dce3c93-5152-4432-ba12-a0c08563c6d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2OTUwNTYsIm5iZiI6MTcxNjY5NDc1NiwicGF0aCI6Ii8xNTU2NzA4MjgvMzMzNzAyODgyLTRkY2UzYzkzLTUxNTItNDQzMi1iYTEyLWEwYzA4NTYzYzZkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQwMzM5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWJjYTMyM2VmNzFhZTNhOWFkZTg4YTc1OGZiMmYyZWZmYzk0ZDdkYzE1YjhiNWRmZDgwYmM1NDA1YjcwYzBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BX6zv_sI_UBnxQSnrzMUEvDrP8HSsPZ51Fkv1L1FvJY)
> 
> Thank you in advance! Mariateresa

Hi~I give up processing smFISH image on Imjoy. Using the Python version of BigFISH(https://big-fish.readthedocs.io/en/stable/) is a better choice. It really runs very well, whether it's looping through multiple smFISH images or the running speed.
